### PR TITLE
Tidy up landing page

### PR DESCRIPTION
**Pull request by ivalaginja**
Addresses #5 

This now looks the same like the landing page we used to have on the Google website. We might want to adapt the text in the future.

### CODE REVIEW

**Review by kjbrooks — APPROVED** [review]
Looks good!

**Comment by ivalaginja** [comment]
Ouch, something went wrong. The landing page is wrong - it rendered correctly from the branch though, so this is confusing.

**Comment by kjbrooks** [comment]
It looks fine if I go to highconaotools.github.io

**Comment by kjbrooks** [comment]
Ohhh I see the problem now.

**Comment by ivalaginja** [comment]
This is how it renders locally, so I am unsure of what is happening here.

Screenshot 2021-04-22 at 22 21 19

**Pull request merged**
