### PR TITLE
Make the table of the "Testbeds" page generate automatically with new testbed data.

### PR DESCRIPTION
**Pull request by KBarjot**
A for loop is generating new rows as testbeds are added in the "_data/testbeds/" folder.

### CODE REVIEW

**Comment by ivalaginja** [comment]
@KBarjot after merging a branch, it's best to make a completely new branch off of the default branch (in our case "master") when you tackle new work. I have now rebased this branch so you can continue on it until we merge it, but you will have to delete it locally and re-check it out form the remote.

I'll have a look at this PR asap.

**Review by ivalaginja — APPROVED** [review]
Very cool! Does what we want it to do and renders correctly.

@KBarjot now is the time to delete you local branch and make a new one off of master when you start the next batch of work :)

**Comment by KBarjot** [comment]
On my side my changes were on the branch kevin_dev, so i thought it was ok.

**Comment by ivalaginja** [comment]
@KBarjot yes there is nothing a priory wrong with that. The problem is if you keep using the same branch after merging it into master (which is what happens when we merge a PR), you will not see the changes that have been merged into master by other branches in the meantime. You could rebase your own branch on master each time you close a PR, but it's usually just easier to delete it completely and create a new one.

So you're totally right, there's nothing that would have started breaking things by staying on your branch, but in case much changed on master in the meantime, you would be working with an outdated repository, which is not great and can lead to merge conflicts later on.

**Pull request merged**
